default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: product_management_system
  username: postgres
  password: '0000'
  host: localhost
  port: 5432

test:
  <<: *default
  database: product_test
  username: postgres
  password: '0000'
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: product_production
    username: postgres
    password: <%= ENV["PRODUCT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: product_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: product_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: product_production_cable
    migrations_paths: db/cable_migrate
